pid: tmp/pids/thin.pid
log: log/thin.log
timeout: 30
max_conns: 1024
port: 30000
max_persistent_conns: 512
chdir: /u/apps/profiles/current
environment: production
servers: 3
address: 0.0.0.0
daemonize: true